name: before-meeting
description: Before a meeting
labels:
  - before_meeting
body:
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Determine how big the meeting is
        - label: What is my personal goal for the meeting
        - label: Do I have enough time?
        - label: What are each teammates roles in the meeting.
        - label: Is there a defined agenda for the meeting