name: monthly
description: Monthly Checklist
title: "yyyy-mm"
labels:
  - monthly
body:
  - type: input
    id: year
    attributes:
      label: Year
      value: "2023"
  - type: dropdown
    id: month
    attributes:
      label: Month
      options:
        - Jan
        - Feb
        - Mar
        - Apr
        - May
        - Jun
        - Jul
        - Aug
        - Sep
        - Oct
        - Nov
        - Dec
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Ask team if allocation is on-target
        - label: Determine if schedule is working well
        - label: Are there any individuals at the partner that are involved in the project that I need to build a relationship with?